title: Yeonsu Jung
logo: /assets/img/logo.jpg
description: Postdoctoral Fellow at <a href="https://seas.harvard.edu/person/yeonsu-jung">Harvard Applied Math</a>.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
